languageCode = "en-us"
title = "zerokspot.com"
metaDataFormat = "yaml"
editor = "em -n"
ignoreFiles = [ "\\.\\#" ]
paginate = 10

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
  unsafe = true

[params]
mainSections = ["weblog", "notes"]

[permalinks]
weblog = "/weblog/:year/:month/:day/:filename/"
notes = "/notes/:year/:month/:day/:filename/"
photos = "/photos/:year/:month/:day/:filename/"
events = "/events/:year/:filename/"

[outputs]
weblog = ["html", "json", "rss"]
page = ["html", "json"]
photos = ["html", "rss"]
archive = ["html"]
events = ["html"]


